# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

name: "Continuous Integration"

jobs:
  run:
    name: "Grumphp"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macOS-latest]
        php-versions: ['7.3', '7.4', '8.0']

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 1

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring,xdebug,pcov

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer update --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Run Grumphp
        run: bin/grumphp run --no-ansi -n

      - name: Send PSALM data
        run: bin/psalm --shepherd --stats
        continue-on-error: true
