# https://docs.github.com/en/actions

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    name: "Grumphp"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        php-versions: ['8.4']

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring
          coverage: pcov
          tools: composer
          ini-values: pcov.enabled=1
          cache: composer

      - name: Validate Composer configuration
        run: composer validate --no-interaction

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run Grumphp
        run: bin/grumphp run --no-ansi -n

      - name: Send PSALM data
        run: bin/psalm --shepherd --stats
        continue-on-error: true
